pipeline {
    agent any
    stages {
        stage('Info') {
            steps {
                echo 'Current working directory: '
                sh 'pwd'
                echo 'List of files: '
                sh 'ls -la'
            }
        }        
        stage('Terraform init') {
            steps {
                echo 'Initialize Terraform'
                sh 'cd examples/aws/infra && terraform init'
            }
        }
        stage('Terraform plan') {
            steps {
                echo 'Prepare Terraform plan in JSON file'
                sh 'cd examples/aws/infra && terraform plan --out tfplan.binary'
                sh 'cd examples/aws/infra && terraform show -json tfplan.binary > tfplan.json'
            }
        }
        stage('Rego policy') {
            steps {
                echo 'Execute Rego policy'
                sh 'opa exec --decision terraform/analysis/allow --bundle examples/aws/policy examples/aws/infra/tfplan.json'
                sh 'opa exec --decision terraform/analysis/score --bundle examples/aws/policy examples/aws/infra/tfplan.json'
            }
        }
    }
}