pipeline {
    agent any
    stages {
        stage('Terraform init') {
            steps {
                echo 'Initialize Terraform'
                sh 'cd examples/aws/infra'
                sh 'terraform init'
            }
        }
        stage('Terraform plan') {
            steps {
                echo 'Prepare Terraform plan in JSON file'
                sh 'terraform plan --out tfplan.binary'
                sh 'terraform show -json tfplan.binary > tfplan.json'
            }
        }
        stage('Rego policy') {
            steps {
                echo 'Execute Rego policy'
                sh 'opa exec --decision terraform/analysis/allow --bundle ../policy tfplan.json'
                sh 'opa exec --decision terraform/analysis/score --bundle ../policy tfplan.json'
            }
        }
    }
}